
name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]
    
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install front-end dependencies
        run: npm install
      - name: Install back-end dependencies
        run: npm --prefix backend install
      - name: Install dependencies (e2e)
        run: npm --prefix e2e_tests install
      - name: Check style
        run: npm run lint
      - name: build
        run: npm run build
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly.io login
        run: |
          echo ${{ secrets.FLY_API_TOKEN }} | flyctl auth login ${{ secrets.FLY_API_TOKEN }} --access-token
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Proxy to fly
        run: |
          flyctl proxy 5432 -a im-only-rating-db &
          FLY_PROXY_PIX=$!
      - name: Start backend
        run: |
          npm --prefix backend run start:test &
          sleep 10
          BACKEND_PID=$!
          echo "Backend PID: $BACKEND_PID"
      - name: Start front-end
        run: |
          npm run dev &
          FRONTEND_PID=$!
          echo "Frontend PID: $FRONTEND_PID"
      - name: Debug DATABASE_URL
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo "DATABASE_URL is not set!"
          else
            echo "DATABASE_URL is set."
          fi
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  
      - name: Install Playwright Browsers
        run: npx --prefix e2e_tests playwright install --with-deps
      - name: e2e tests
        run: npm run test:e2e
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Stop front, backend and fly
        run: |
          echo "Stopping front and backend"
          kill $BACKEND_PID
          kill $FRONTEND_PID
          kill $FLY_PROXY_PID
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
