name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install front-end dependencies
        run: npm install
      - name: Install back-end dependencies
        run: npm --prefix backend install
      - name: Install dependencies (e2e)
        run: npm --prefix e2e_tests install
      - name: Check style
        run: npm run lint
      - name: build
        run: npm run build
        env:
          VITE_TOKEN: ${{ secrets.VITE_TOKEN }}
          VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}
          ISBNDB_KEY: ${{ secrets.ISBNDB_KEY }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly.io login
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl status -a im-only-rating-db
      - name: Proxy to fly
        run: |
          flyctl proxy 5432 -a im-only-rating-db &
          FLY_PROXY_PIX=$!
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Install Playwright Browsers
        run: npx --prefix e2e_tests playwright install --with-deps

      - name: Print used ports
        run: netstat -tulnp

      - name: e2e tests
        run: npx wait-on tcp:localhost:5432 && npm run test:e2e
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          VITE_TOKEN: ${{ secrets.VITE_TOKEN }}
          VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}
          OPEN_LIBRARY: ${{ secrets.OPEN_LIBRARY }}
          VITE_TWITCH_CLIENT_ID: ${{ secrets.VITE_TWITCH_CLIENT_ID }}
          VITE_TWITCH_CLIENT_SECRET: ${{ secrets.VITE_TWITCH_CLIENT_SECRET }}
          ISBNDB_KEY: ${{ secrets.ISBNDB_KEY }}
      - name: Copy Frontend Built to Backend
        run: |
          rm -rf backend/dist
          cp -r dist backend/
      - name: Deploy app
        if: ${{ (github.event_name == 'push') && (!contains(join(github.event.head_commit.message, ', '), '#skip')) }}
        run: cd backend && flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Save Playwright logs
        if: always()
        run: |
          mkdir -p artifacts
          cp -r e2e_tests/playwright-report artifacts/
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: artifacts/
          retention-days: 30
      - name: Upload Playwright traces
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: e2e_tests/test-results/**/*.zip

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
